FROM python:3.11-slim

ENV PYTHONUNBUFFERED=True

WORKDIR /usr/src/app

COPY ./requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY ./src ./src
COPY ./artifacts ./artifacts

ENV PYTHONPATH=/usr/src/app

EXPOSE 4010

CMD [ "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "4010"]

